### ISSUE TITLE
Impossible to access an attribute ("lat") on a null variable.

### ISSUE THREAD

**Issue by habibun** [ld-web/medium-sf-di-solid-geocoding#3]
I am getting this error in the show page

local URL: http://127.0.0.1:81/destination/4

below is the db value  for destination id: 4

id,   country_id,   city,          coordinates_lat,   coordinates_lng
'4',   '1',                'Dhaka',   '37.4224764',        '-122.0842499'

**Comment by ld-web** [comment]
Your record looks ok to me.

Several steps I would get to investigate further :

- In your `DestinationController` file, in the `show` controller, dump the `$destination` var :

```php
// Put the "dd" instruction on line 59, before the "return $this->render..."
dd($destination);
```

It should show you if the record was successfully fetched from the database, using the Doctrine ParamConverter.

- If your record is successfully retrieved, then check if your template is ok, you should have on line 20 :

```twig
<td>{{ destination.coordinates.lat }}</td>
```

Since the `$coordinates` attribute is an Embedded attribute in the `Destination` entity, you have to access it like an attribute.

If you're still struggling after these checks, don't hesitate to send me a link to a Github repo and I'll review it.

Hope this helps !

**Comment by habibun** [comment]
here is my repo link: https://github.com/habibun/symfony-solid

**Comment by ld-web** [comment]
Ok, it just looks like you're missing some dependencies.

First, you're missing the `sensio/framework-extra-bundle` dependency, which includes the [ParamConverter](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html) feature.

The Doctrine ParamConverter is the one supposed to fetch automatically the `Destination` entity in your `show` controller, based on the `id` given in the route.

So, you just have to install the missing package with composer : `composer require sensio/framework-extra-bundle`.

But then, you are going to run into another problem. When you want to see the record (`show` controller), your application won't be able to generate a CSRF token to display a "delete" button.

This will happen because you're missing the `symfony/security-bundle` package, which embeds the `symfony/security-csrf` package. So basically, the Security Component is missing.

So, same as the Framework Extra Bundle : `composer require symfony/security-bundle`.

Then it should be okay 👍

**Comment by habibun** [comment]
you are absolutely right. thanks
